### ISSUE TITLE
I'm trying to reproduce...

### ISSUE THREAD

**Issue by Zhaodouad** [enveda/kgem-ensembles-in-drug-discovery#4]
Hello, when I ran get_predictions.py, the following problem occurred. Do you know how to solve it?
<img width="880" alt="微信图片_20231206174706" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/044964fc-309f-4dd5-88eb-f3b84073a8fd">

**Comment by YojanaGadiya** [comment]
@Zhaodouad could you provide the details of the version and packages you have in your environment for us to look more into? 

/cc @danirivas

**Comment by Zhaodouad** [comment]
Thank you for your reply. I am using colab provided by Google. The following are the packages in the environment.
<img width="679" alt="微信图片_20231206203104" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/ca523967-b96b-4616-b9c8-8c5e4b151556">
<img width="579" alt="微信图片_20231206203152" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/8ac676b8-6b8a-4ed2-9f0a-d82c5619d8d2">
<img width="598" alt="微信图片_20231206203207" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/f62c7f26-1e68-4ea9-8f6f-709b16c5bb9d">
<img width="518" alt="微信图片_20231206203217" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/a56f68d5-918b-48ef-b13f-62aa53373c5d">
<img width="608" alt="微信图片_20231206203246" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/5cc8347e-fb78-431c-9e81-541e4b1d36df">
<img width="626" alt="微信图片_20231206203255" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/0c50519c-ea41-4f43-8d41-e917a6697860">
<img width="482" alt="微信图片_20231206203326" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/42c74325-96f1-4f72-8dc1-b1c1b948df86">
<img width="422" alt="微信图片_20231206203334" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/dbdf2a88-c6c9-470c-b8e2-c816fdc75321">
![微信图片编辑_20231206203139](https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/0c83bf3e-79c5-4af9-97ee-c4ea03228c6f)


> @Zhaodouad could you provide the details of the version and packages you have in your environment for us to look more into?
> 
> /cc @danirivas

**Comment by Zhaodouad** [comment]
Hi @YojanaGadiya ，When I installed pykeen1.8.0, the following error was reported:
<img width="980" alt="1701950995271" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/8b3c71b3-0038-474b-ac4a-d8a1f5426e07">
Can you show me the details of the version and packages you have in your environment?

**Comment by ddomingof** [comment]
I see, the requirements.txt for PyKEEN used scikit-learn and that got deprecated. We cannot fix that unfortunately because that version is already in PyPi. Please follow these instructions:
1. Download PyKEEN src code from GitHub when the version was 1.8.0 [link here](https://github.com/pykeen/pykeen/tree/12c3da815f03d17bca78d5255c7c4141625b9de7)
2. Open your virtualenv
3. Go to that folder where you downloaded PyKEEN 1.8.0
4. Change [setup.cfg](https://github.com/pykeen/pykeen/blob/12c3da815f03d17bca78d5255c7c4141625b9de7/setup.cfg#L61C5-L61C12) and remove sklearn.
5. `pip install -e .`
6. Now you have PyKEEN installed so you can install sklearn in the correct version using the new name it has.
